### ISSUE TITLE
New icons break on mastodon air

### ISSUE THREAD

**Issue by SympathyTea** [magnusarge/Mastodon-Air#2]
Recent changes to glitch-soc has introduced Material Icons from recent commits. The boost icon specifically will not turn blue on mastodon air, and looks normal without the extension. I have talked to my instance's admin regarding this change, [and was told to contact you instead regarding this.](https://wetdry.world/@esm/111757228419887058)

I'm not fully sure where I am supposed to send bug reports regarding this plugin, but I found the issues page from your website. I apologize if this isn't the correct way to send bug reports.

First image is with mastodon air enabled, second is disabled.

![firefox_vSNs6QUYZH](https://github.com/magnusarge/Mastodon-Air/assets/116274772/547e64b9-ffe5-4706-84ef-0d157ebfe784)
![firefox_CipcPAX1qr](https://github.com/magnusarge/Mastodon-Air/assets/116274772/fbd35679-406a-498d-b106-9ba926232b1f)

**Comment by magnusarge** [comment]
Thank you for reporting the issue!
The new icons in Glitch edition uses svg-s directly instead of Font Awesome's css.
Good news is that this is fixable, give me few days to update the code.
However, since Glitch is forked from the upstream version of Mastodon for which Mastodon Air was written, I cannot give any guarantees to fully support this edition in the future.

**Comment by magnusarge** [comment]
Fixed in version 2.1.4
